# Site Settings
name: 上海能运金属构件有限公司
title: 围栏_护栏_机场隔离栅_金属防腐网-上海能运金属构件Newiin
description: 上海能运金属构件有限公司主要生产围栏,护栏,机场围界、开发区围栏、小区围栏、道路围栏、隔离栅、道路设施、金属防腐网及涂装设备的防腐设备公司，公司引用先进的涂装技术，对金属表面通过高温氧化后进行浸塑处理，使金属表面同空气彻底隔绝，起到非常好的防腐作用。
keywords: 围栏,护栏,隔离栅,机场围界,金属防腐网
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: youremail@xyz.com
# disqus_username: disqus_username
show_hero: true
menu:
  - title: 首页
    url: /
  - title: 关于
    url: /about
  - title: 联系
    url: /contact
  - title: 新闻
    url: /news

image_path: /assets/img/images/
show_time: false

# Social Media Settings
# Remove the item if you don't need it
# github_username: github_username
# facebook_username: facebook_username
# twitter_username: twitter_username
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-169433022-1"
language: "zh"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
contract_us: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
# version: v3.1.0

# Advanced Settings
translations:
  text:
    new_post: "最新"
    see_also: "相关推荐"
    search: "搜索"
    author: "作者"
    share: "分享"
    comments: "评论"
  button:
    read_now: "企业信息"
    share_on_twitter: "Share on Twitter"
    share_on_facebook: "Share on Facebook"
  pagination:
    page: "页"
    of: "/"
    next_page: "下一页"
    next_post: "上一页"
  recommendation:
    text: "推荐阅读"
    back_btn: "返回顶部"
  error_404:
    title: "Page not found :("
    message: "I'm sorry. We couldn't find the page you are looking for."
    image_alt: "404 - Page not found"
  contact:
    title: "Talk to me"
    subject: "New contact!"
    submit_btn: "Send"
    placeholders:
      name: "Your name"
      email: "Your e-mail"
      message: "Your message"
    errors:
      locale: "en"
      empty_name: "Name is required"
      empty_email: "Email is required"
      invalid_email: "Email is invalid"
      empty_message: "Message is required"
    after_send:
      title: "Message sent!"
      message: "Thank you for sending me a message. I'm going to answer ASAP."
